import type { Metadata } from "next";
import { Geist, Playfair_Display } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import InstagramSection from "@/components/InstagramSection";
import Nav from "@/components/Nav";
import { ReactQueryClientProvider } from "@/components/ReactQueryClientProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const playfairDisplay = Playfair_Display({
  variable: "--font-playfair-display",
  subsets: ["latin", "latin-ext", "cyrillic", "vietnamese"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryClientProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${playfairDisplay.variable} antialiased`}
        >
          <Nav />
          {children}
          <InstagramSection />
          <Footer />
        </body>
      </html>
    </ReactQueryClientProvider>
  );
}
